### ISSUE TITLE
Synonyms

### ISSUE THREAD

**Issue by doingweb** [washingtonstateuniversity/WSU-spine#114]
I've been learning about and experimenting with the grid system, and I noticed [what appears to be a synonym for `.gutterless`](https://github.com/washingtonstateuniversity/WSU-spine/blob/042902babd16d1ac8d029050574f252ac09f0cf7/styles/sass/skeleton/_gutter.scss#L159):

``` scss
.gutterless,
.gutless {
    padding-left: 0px !important;
    padding-right: 0px !important;
    }
```

Does `.gutless` have a purpose outside of being a synonym for `.gutterless`? A global text search of the repo tells me no, but that of course can't reveal any plans you might have for it in the future.

If it _is_ only a synonym, I move to take it out, since at best it's just confusing (and a little fun -- "gutless", I get it), and at worst it's noise that consumers can become dependent on.

So what's up with it?
