### ISSUE TITLE
nav icon missing in some mobile devices

### ISSUE THREAD

**Issue by quantumJLBass** [washingtonstateuniversity/WSU-spine#167]
From emails, this seems to be the issue, on some deceives the icon for the nav doesn't show.  This is an example provided by @slocker3 
![screenshot_2014-11-06-18-17-59](https://cloud.githubusercontent.com/assets/43837/4949039/f789fd2a-6600-11e4-83d9-5c08b8e571dd.png)

After testing on my end I have fail to reproduce it.  Nicole Wood has seen it on 
"business, brand, provost, and ucomm sites. On my Galaxy S4 it renders without the menu icon on Dolphin"

@jeremyfelt confirms he sees the there is no issue in iOS 6 and an Android device.  
I can confirm everything shows fine on an HTC One native chrome browser, but fails on the Native custom HTC browser 

This is what I have so far.  At this time I believe it's not a z-index issue, nor is it a issue of the media queries.  If I flip the size on my devices there is no change and they span a few sizes.

I think these are the rules at fault here

``` css

#binder.fluid #spine button#shelve {
    display: block;
}
button#shelve {
    background: url("https://repo.wsu.edu/spine/1/icons/menu.svg") no-repeat scroll 20px center transparent;
    border: 0 none;
    display: none;
    height: 50px;
    left: 0;
    outline: 0 none;
    position: absolute;
    top: 0;
    width: 100px;
    z-index: 0;
}
```
